# Generated by Django 4.2.7 on 2023-11-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artclass', '0003_artclass_image_artclass_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artclass',
            options={'verbose_name_plural': 'Art Classes'},
        ),
        migrations.AddField(
            model_name='artclass',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
